### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by rebecca0011** [jzhangbs/DSM#2]
Thanks for your code!But I got an error and don't know how to deal with
`Traceback (most recent call last):
  File "train.py", line 127, in <module>
    loss.backward()
  File "/home/rc/anaconda3/envs/DL/lib/python3.7/site-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/rc/anaconda3/envs/DL/lib/python3.7/site-packages/torch/autograd/__init__.py", line 156, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1, 32, 256, 512]], which is output 0 of ReluBackward0, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
`

**Comment by jzhangbs** [comment]
try to remove all the `inplace=True` in `nn_utils.py`?
